name       : python-trove-classifiers
version    : 2023.7.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/t/trove-classifiers/trove-classifiers-2023.7.6.tar.gz : 8a8e168b51d20fed607043831d37632bb50919d1c80a64e0f1393744691a8b22
homepage   : https://github.com/pypa/trove-classifiers
license    : Apache-2.0
component  : programming.python
summary    : PCanonical source for classifiers on PyPI
description: |
    Classifiers categorize projects per PEP 301. Use this package to validate classifiers in packages for PyPI upload or download.
builddeps  :
    - python-build
    - python-calver
    - python-installer
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
